# Generated by Django 5.2.17 on 2026-08-14 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_key',
            field=models.PositiveIntegerField(default=1, help_text='A numeric key up to 6 digits for password recovery.Entered ONCE .', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
    ]
