# Generated by Django 5.2.17 on 2026-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_customuser_security_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
